name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck bats

      - name: Run tests + lint + package
        run: |
          make VERSION="${{ steps.get_version.outputs.VERSION }}"
          make release VERSION="${{ steps.get_version.outputs.VERSION }}"
          mv dist/symlinkit-${{ steps.get_version.outputs.VERSION }}.tar.gz .
          mv dist/symlinkit-${{ steps.get_version.outputs.VERSION }}.tar.gz.sha256 SHA256SUMS
          cat SHA256SUMS

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            symlinkit-*.tar.gz
            SHA256SUMS
          body: |
            ## symlinkit ${{ steps.get_version.outputs.VERSION }}

            See [CHANGELOG.md](https://github.com/ctrl-alt-adrian/symlinkit/blob/main/CHANGELOG.md) for details.

            ### Installation

            ```bash
            curl -fsSL https://raw.githubusercontent.com/ctrl-alt-adrian/symlinkit/main/install.sh | bash
            ```

            Or download and extract the tarball manually.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
